### ISSUE TITLE
Flexible Windows extension, background color ignored on one of two created windows

### ISSUE THREAD

**Issue by BroadcastGames** [erkyrath/quixe#24] opened 2016-10-13 23:59 UTC
On this generated gblorb, the command 'side window' should open two additional windows, of which the right-most should have a peach background color. This works correctly in Gargoyle, but not on Quixe 2.1.5.  The other window (border window) does get correctly colored.

http://eblong.com/zarf/glulx/quixe/quixe/play-remote.html?story=https%3A%2F%2Fdrive.google.com%2Fuc%3Fexport%3Ddownload%26id%3D0B452Xi1yb0BTc0xXYzQtcFllOTQ&enter=Play+it%21

The Inform  source code is here:

http://www.intfiction.org/forum/viewtopic.php?f=7&t=20651&p=114090#p114040

Also of note, if you go "west" in the same demo - there is text that should have different foreground and background colors. This works in Gargyle but in Quixe the style changes are ignored.

**Comment by curiousdannii** [comment] 2016-10-15 06:10
Background colours of text windows are implemented by setting background colour style hints, none of which aren't supported by Quixe. So this is essentially a duplicate of https://github.com/erkyrath/glkote/issues/5.

Using style hints to set the background colour of the whole window has always felt like a hack to me. Theoretically glk_window_set_background_color() could be extended to support setting the background colour of all windows, but that's a call for Zarf to make. The hack works currently, except for the Gnome IDE.

**Closed** 2016-10-30 18:58 UTC
